### ISSUE TITLE
Black boxes appear every time a new scene/object loads

### ISSUE THREAD

**Issue by fcampbell7** [lachlanpye/399-Unity-Project#10]
In the gameplay branch

**Comment by tyhindmarsh** [comment]
where are the black boxes on screen? are they like in place of the object being loaded in or something?

**Comment by fcampbell7** [comment]
Yeah it seems like it. A few notable ones were sometimes when you change area in the Forest, when the boss first appears, and when the death UI appears

**Comment by fcampbell7** [comment]
it is an issue with the transition panel scaling within the Unity editor. Works in a smaller window, and only seems to be specific to me

**Comment by tyhindmarsh** [comment]
we had the black box issue again with a built game at 960x720, which is the size we're looking to ship at

**Comment by fcampbell7** [comment]
Fixed
