### ISSUE TITLE
Player appears in front of tree

### ISSUE THREAD

**Issue by tyhindmarsh** [lachlanpye/399-Unity-Project#24]
lol
![infront](https://user-images.githubusercontent.com/61497179/97125714-a88a4080-1799-11eb-9fe4-b5ea268bbea6.PNG)

**Comment by tyhindmarsh** [comment]
if the player walks up a bit he goes behind the tree so it might be something to do with where the centre point is on the tree. so either increase the height of the collider so the player can't walk that far down the tree or change the pivot point on the tree to be lower

**Comment by lachlanpye** [comment]
Base point of tree is now set
