### ISSUE TITLE
Player in different area to camera

### ISSUE THREAD

**Issue by tyhindmarsh** [lachlanpye/399-Unity-Project#29]
The camera teleported to the pond while the father teleported to the T area and look damage as normal and stuff
![position](https://user-images.githubusercontent.com/61497179/97156100-160a9100-17db-11eb-85f1-9c88df62f3a0.PNG)
![camera](https://user-images.githubusercontent.com/61497179/97156111-186ceb00-17db-11eb-9e6b-7aca3bf8e02b.PNG)

**Comment by tyhindmarsh** [comment]
Don't know how to replicate it other than just play testing until you end up in the T block. I came in from the right so just walk left whenever you get the opportunity. if you end up in the T coming in from the right and you can actually see that and not the pond area, then it's probably no longer an issue

**Comment by lachlanpye** [comment]
I was able to get to the pond from the right and the T from the right, so I don't think this is an issue unless someone manages to replicate it
