### ISSUE TITLE
Interaction icon missing on altar

### ISSUE THREAD

**Issue by tyhindmarsh** [lachlanpye/399-Unity-Project#31]
![no icon](https://user-images.githubusercontent.com/61497179/97159284-7dc2db00-17df-11eb-974f-5db7fc6628c5.PNG)

**Comment by tyhindmarsh** [comment]
not missing on the fireflies tho

**Comment by tyhindmarsh** [comment]
also missing on the confessional

**Comment by lachlanpye** [comment]
Fixed
