### ISSUE TITLE
Player right attack ends with player in different position to the walk right animation

### ISSUE THREAD

**Issue by tyhindmarsh** [lachlanpye/399-Unity-Project#56]
After the right stab animation finishes, the player appears to teleport a couple of frames to the right meaning the stab animation and walk right animation aren't aligned properly. This needs to be fixed by making sure both animations are on the same position in the canvas in aseprite

End of stab frame:
![end of stab](https://user-images.githubusercontent.com/61497179/97239428-7ee02080-1850-11eb-8cd0-55402f34c923.PNG)

Start of walk frame:
![start of walk](https://user-images.githubusercontent.com/61497179/97239443-86072e80-1850-11eb-826e-85f95750be84.PNG)

As you can see, the walk is further to the right

**Comment by lachlanpye** [comment]
Should now be fixed
