### ISSUE TITLE
Flash doesn't always stun boss

### ISSUE THREAD

**Issue by tyhindmarsh** [lachlanpye/399-Unity-Project#59]
Not sure if there's like a timer that prevents spamming the flash ability to stun the boss but the player can still trigger the flash by pressing Q or if it's a bug that the boss isn't being stunned. Let me know, Lachlan, and I can fix it

**Comment by lachlanpye** [comment]
Yeah the timer was set to 1 for testing purposes, you can set the cooldown on Flash Ability Cooldown on the player object

**Comment by tyhindmarsh** [comment]
Just reopening so I can prevent the player from being able to flash while the timer is counting so they don't think the game is bugged or something

**Comment by tyhindmarsh** [comment]
When in darkness it still doesn't work, the boss doesn't go into the last frame of the stun animation

**Comment by tyhindmarsh** [comment]
Stopped the animator from being slowed down during darkness and that fixed the issue

**Comment by tyhindmarsh** [comment]
checked if boss is stunned before every animation change, i think it was the walk anims in the update function that caused the issues
