### ISSUE TITLE
Collision problems in outsideHouse scene

### ISSUE THREAD

**Issue by jaunzo** [lachlanpye/399-Unity-Project#64]
![collision1](https://user-images.githubusercontent.com/65937191/97252356-a940d680-186e-11eb-9bec-85568d917573.gif)
![collision2](https://user-images.githubusercontent.com/65937191/97252612-413ec000-186f-11eb-8ca2-e459d93df685.gif)

**Comment by jaunzo** [comment]
Also colliding with invisible object somewhere around the red circle below in the second area of the scene
![invisible_collision](https://user-images.githubusercontent.com/65937191/97252665-69c6ba00-186f-11eb-916a-96c8ec60a068.PNG)

**Comment by lachlanpye** [comment]
Fixed all collisions and object base points
