### ISSUE TITLE
Attack indicator still active in boss fight after stunning the boss and stabbing it

### ISSUE THREAD

**Issue by lachlanpye** [lachlanpye/399-Unity-Project#82]
If you stun the boss and stab it, the stab icon doesn't disappear and it still makes the stabbing noise, so it looks like the player is attacking the boss even though they don't do any extra damage after that first stab

**Comment by tyhindmarsh** [comment]
@jaunzo start by sorting the stabbing noise being played and if the stab icon is easy enough to fix alongside that then you can do that too and close the issue. otherwise lmk once the noise is fixed and i'll sort the stab icon
