### ISSUE TITLE
Can see right and bottom edge of town map in intro cutscene

### ISSUE THREAD

**Issue by tyhindmarsh** [lachlanpye/399-Unity-Project#95]
it looks like the background is too far up and to the left

**Comment by tyhindmarsh** [comment]
Can also see black bar on the right if walk to the right of the screen in the town area
![right](https://user-images.githubusercontent.com/61497179/97531178-84886280-1a18-11eb-91fc-72182356a456.PNG)

**Comment by lachlanpye** [comment]
Both issues should now be fixed
